### ISSUE TITLE
Syntax error I can't debug

### ISSUE THREAD

**Issue by cepinos** [truora/minidyn#31]
I am getting the next syntax error: 
```
panic: syntax error: ERROR: index assignation for "NULL" type is not supported [recovered]
	panic: syntax error: ERROR: index assignation for "NULL" type is not supported
```

expressionAttributeValues are:
```
{":billing_hub":{"B":null,"BOOL":null,"BS":null,"L":null,"M":null,"N":null,"NS":null,"NULL":null,"S":"dummy","SS":null},":birth_place":{"B":null,"BOOL":null,"BS":null,"L":null,"M":null,"N":null,"NS":null,"NULL":null,"S":"1","SS":null},":client_id":{"B":null,"BOOL":null,"BS":null,"L":null,"M":null,"N":null,"NS":null,"NULL":null,"S":"TCIHBJ","SS":null},":manual_validation_result__is_valid":{"B":null,"BOOL":true,"BS":null,"L":null,"M":null,"N":null,"NS":null,"NULL":null,"S":null,"SS":null},":manual_validation_result__message":{"B":null,"BOOL":null,"BS":null,"L":null,"M":null,"N":null,"NS":null,"NULL":null,"S":"dummy","SS":null},":manual_validation_result__tasks_results":{"B":null,"BOOL":null,"BS":null,"L":[{"B":null,"BOOL":null,"BS":null,"L":null,"M":{"name":{"B":null,"BOOL":null,"BS":null,"L":null,"M":null,"N":null,"NS":null,"NULL":null,"S":"fake-picture","SS":null},"task_status":{"B":null,"BOOL":null,"BS":null,"L":null,"M":null,"N":null,"NS":null,"NULL":null,"S":"invalid","SS":null}},"N":null,"NS":null,"NULL":null,"S":null,"SS":null}],"M":null,"N":null,"NS":null,"NULL":null,"S":null,"SS":null},":manually_labeled":{"B":null,"BOOL":true,"BS":null,"L":null,"M":null,"N":null,"NS":null,"NULL":null,"S":null,"SS":null},":manually_reviewed":{"B":null,"BOOL":true,"BS":null,"L":null,"M":null,"N":null,"NS":null,"NULL":null,"S":null,"SS":null}}
```

expressionAttributeNames are: 
```
{"#billing_hub":"billing_hub","#birth_place":"birth_place","#client_id":"client_id","#is_valid":"is_valid","#manual_validation_result":"manual_validation_result","#manually_labeled":"manually_labeled","#manually_reviewed":"manually_reviewed","#message":"message","#tasks_results":"tasks_results"}
```

my updateExpression is:
```
SET #manual_validation_result.#is_valid = :manual_validation_result__is_valid, #manual_validation_result.#message = :manual_validation_result__message, #manual_validation_result.#tasks_results = :manual_validation_result__tasks_results, #birth_place = :birth_place, #client_id = :client_id, #manually_labeled = :manually_labeled, #manually_reviewed = :manually_reviewed, #billing_hub = :billing_hub
```

I don't see any NULL type in those values. This is the trace error:
```
goroutine 9 [running]:
testing.tRunner.func1.2({0x16b1660, 0xc000449e80})
	/usr/local/Cellar/go/1.17.2/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/Cellar/go/1.17.2/libexec/src/testing/testing.go:1212 +0x218
panic({0x16b1660, 0xc000449e80})
	/usr/local/Cellar/go/1.17.2/libexec/src/runtime/panic.go:1038 +0x215
github.com/truora/minidyn.(*table).interpreterUpdate(0xc000155400, {{0x17d336b, 0x15}, {0xc0002f84e0, 0x18e}, 0xc0002f4d20, 0xc0002f4a50, 0xc0002f4a80})
	/Users/cesar/go/pkg/mod/github.com/truora/minidyn@v0.0.0-20211117195425-89363e087973/table.go:479 +0xe7
github.com/truora/minidyn.(*table).update(0xc000155400, 0xc000076ea0)
	/Users/cesar/go/pkg/mod/github.com/truora/minidyn@v0.0.0-20211117195425-89363e087973/table.go:520 +0x293
github.com/truora/minidyn.(*Client).UpdateItem(0xc0000929b0, 0xc000076ea0)
	/Users/cesar/go/pkg/mod/github.com/truora/minidyn@v0.0.0-20211117195425-89363e087973/client.go:311 +0x185
github.com/truora/minidyn.(*Client).UpdateItemWithContext(0x169a5a0, {0xc0002f4cc0, 0x17b7b73}, 0x6, {0x2, 0xc0002fc280, 0x27d})
	/Users/cesar/go/pkg/mod/github.com/truora/minidyn@v0.0.0-20211117195425-89363e087973/client.go:325 +0x1c
bitbucket.org/truora/scrap-services/documents-recognition/storage.UpdateDocument({0x1a01410, 0xc000026098}, 0xc0004d7b00)
	/Users/cesar/go/src/bitbucket.org/truora/scrap-services/documents-recognition/storage/storage.go:179 +0x582
bitbucket.org/truora/scrap-services/documents-recognition/storage.TestUpdateDocumentWithManualValidationResult(0x0)
	/Users/cesar/go/src/bitbucket.org/truora/scrap-services/documents-recognition/storage/storage_test.go:535 +0x20a
testing.tRunner(0xc0005036c0, 0x18129e8)
	/usr/local/Cellar/go/1.17.2/libexec/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/Cellar/go/1.17.2/libexec/src/testing/testing.go:1306 +0x35a
exit status 2
FAIL	bitbucket.org/truora/scrap-services/documents-recognition/storage	0.032s
```

As you can see the panic is trigger by line:
```
[[0xc0002f4d20, 0xc0002f4a50, 0xc0002f4a80})
	/Users/cesar/go/pkg/mod/github.com/truora/minidyn@v0.0.0-20211117195425-89363e087973/table.go:479](https://github.com/truora/minidyn/blob/main/table.go#L479)](https://github.com/truora/minidyn/blob/main/table.go#L479)
```

This is the native sdk interpreter, but I can't understand, I think syntax is ok. Is there something wrong with my expressions?

### Update
I printed native error and I god this error:
```
panic: lang interpreter error: syntax error: ERROR: index assignation for "NULL" type is not supported
native interpreter error: unsupported expression or attribute type: updater not found for "SET #client_id = :client_id, #manually_labeled = :manually_labeled, #billing_hub = :billing_hub, #birth_place = :birth_place, #manually_reviewed = :manually_reviewed, #manual_validation_result.#is_valid = :manual_validation_result__is_valid, #manual_validation_result.#message = :manual_validation_result__message, #manual_validation_result.#tasks_results = :manual_validation_result__tasks_results" expression in table "documents-recognition"
```

This is the pr to print the new error
https://github.com/truora/minidyn/pull/32

**Comment by cepinos** [comment]
Forget it, I found the problem, I had to insert the document first and then update it.
```
err := StoreDocument(context.Background(), document)
c.NoError(err)

doc, err := UpdateDocument(context.Background(), document)
c.NoError(err)
```
